### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zilockegaming** [qbcore-framework/qb-vehiclekeys#159] opened 2022-09-05 19:45 UTC
hey i have a issue with my qb-vehiclekeys when i spawn a vehicle or when someone wants to drive my veheicle tyhe thores are automaticly locked i looked for settings but could not find it i also updated it
but is lock

**Comment by tom-osborne** [comment] 2022-09-05 22:37
This is a duplicate of #156

**Closed** 2022-11-06 18:55 UTC
Labels: bug, duplicate
