### ISSUE TITLE
[BUG] unlocked vehicle becomes locked

### ISSUE THREAD

**Issue by Dersicko** [qbcore-framework/qb-vehiclekeys#113] opened 2022-05-20 19:11 UTC
When the person who has vehicle keys leaves the car and leaves the car unlocked , someone else without vehicle keys cant enter it.
the car become auto locked

**Comment by SamueleAbbate** [comment] 2022-05-20 20:15
I solved this problem by creating a table called closed in the database thanks to this SQL code: ALTER TABLE `player_vehicles`  
ADD COLUMN `closed` int(11) DEFAULT 0; 
where 0 means the unlocked car then in the fxmanifest you have to enter 
client_script {
    '@oxmysql/lib/MySQL.lua',
    'client/main.lua'
}
and then in the client.lua you have to enter this code from line 79
 MySQL.Async.fetchAll('SELECT `chiusa` FROM `player_vehicles` WHERE `plate` = @plate', { ['@plate'] = plate }, 
                function(result)
                    
                    if result == 0 then

                    -- if closed then
                            if GetPedInVehicleSeat(vehicle, -1) == PlayerPedId() and not HasKeys(plate) and not isBlacklistedVehicle(vehicle) then
                                sleep = 5

                                local vehiclePos = GetOffsetFromEntityInWorldCoords(vehicle, 0.0, 1.0, 0.5)
                                DrawText3D(vehiclePos.x, vehiclePos.y, vehiclePos.z, "~g~[H]~w~ - Cerca chiavi")
                                SetVehicleEngineOn(vehicle, false, false, true)

                                if IsControlJustPressed(0, 74) then
                                    Hotwire(vehicle, plate)
                                end
                            end
                    -- end

                    end
                    print(json.encode(result))
                end)
![fixkey](https://user-images.githubusercontent.com/91976683/169602983-1241c2e1-e06b-4bdf-92d3-4e79a6df93ca.PNG)

**Comment by Dersicko** [comment] 2022-05-21 06:13
Would this solve the issue for non player owned cars too?

**Comment by SamueleAbbate** [comment] 2022-05-21 16:11
this was the goal but i don't know why the script stopped working now i'm working to fix it permanently if i can do it i will send everything here ...
stay tuned

**Comment by SamueleAbbate** [comment] 2022-05-21 16:35
I'm done ... now people even if they don't own the machine and the owner forgot to close it ... you just have to take the files and put them in place of the current ones in addition I have implemented the fact that if a player is mechanical it can always open the machines to disable this setting commented from lines 62 to 63 ... the variables are written in Italian I apologize in advance. I hope it will be useful to you

[newclient.txt](https://github.com/qbcore-framework/qb-vehiclekeys/f
[newmanifest.txt](https://github.com/qbcore-framework/qb-vehiclekeys/files/8747976/newmanifest.txt)
iles/8747971/newclient.txt)
[editsql.txt](https://github.com/qbcore-framework/qb-vehiclekeys/files/8747981/editsql.txt)

[newserver.txt](https://github.com/qbcore-framework/qb-vehiclekeys/files/8747974/newserver.txt)

**Comment by SamueleAbbate** [comment] 2022-05-21 16:38
[newclient.txt](https://github.com/qbcore-framework/qb-vehiclekeys/files/8747991/newclient.txt)

**Comment by Dersicko** [comment] 2022-05-21 21:49
Thank you for the help! but sadly this does not work entirely for me since now parked cars are also unlocked

**Comment by SamueleAbbate** [comment] 2022-05-21 22:21
really strange to me it works perfectly ... what kind of car do you have left open? those of the NPCs?

**Comment by Dersicko** [comment] 2022-05-21 22:35
Yes parked NPC cars

**Comment by SamueleAbbate** [comment] 2022-05-21 22:37
try uncommenting the code from lines 85 to 95

**Comment by SamueleAbbate** [comment] 2022-05-21 22:39
in this way he will break the window but he will have to steal the keys and the police will arrive

**Comment by SamueleAbbate** [comment] 2022-05-21 22:40
but so everyone will have to steal it

**Comment by SamueleAbbate** [comment] 2022-05-21 22:42
anyway tomorrow I'll look for a way to solve even this small problem

**Comment by Dersicko** [comment] 2022-05-21 22:42
Okay i will try this, thank you

**Comment by JordanBScott** [comment] 2022-05-24 22:24
Hey! Thanks for these! I am gonna test them soon, but I wanted to make sure I did it right.
I replace the current server.lua with your newserver.txt
then replace the current client.lua with your newclient.txt
then create this column in the player_vehicle database section... (see image) ![Screenshot (18)](https://user-images.githubusercontent.com/99845881/170141901-6a016667-bb2b-4702-9d2b-a77a196d1a36.png)
the put this in the fxmanifest 
client_script {
'@oxmysql/lib/MySQL.lua',
'client/main.lua'
}
Is this all the correct steps? Thanks!

**Comment by SamueleAbbate** [comment] 2022-05-28 20:23
> Ehi! Grazie per questi! Li proverò presto, ma volevo assicurarmi di averlo fatto bene. Sostituisco l'attuale server.lua con il tuo newserver.txt quindi sostituisco l'attuale client.lua con il tuo newclient.txt quindi creo questa colonna nella sezione del database player_vehicle ... (vedi immagine) quindi inserisco questo in fxmanifest client_script { '@ oxmysql/lib/MySQL.lua', 'client/main.lua' } Sono tutti i passaggi corretti? Grazie!![Schermata (18)](https://user-images.githubusercontent.com/99845881/170141901-6a016667-bb2b-4702-9d2b-a77a196d1a36.png)

yes

**Comment by SamueleAbbate** [comment] 2022-05-28 20:25
> Leaves all car doors unlocked when fix applied

i'll fix it soon

**Comment by Dabcity** [comment] 2022-05-28 22:08
No worries, went with a different script to handle the vehicle keys.

**Comment by FizzGamingJR** [comment] 2022-06-04 13:32
> No worries, went with a different script to handle the vehicle keys.

Hello there, I am having this issue as well.
If you don't mind me asking, what script are you now using?
The players on my server are getting frustrated with the fact they are unable to enter another players vehicle without the key holder being in the passenger or drivers seat, so another option to use until the bug is fixed would be much appreciated :)

**Comment by Dabcity** [comment] 2022-06-04 18:49
Jaksams script.

**Comment by Xodus989** [comment] 2022-07-16 03:59
Has there been any updates to fix this? I'd rather not implement a new key system.

**Comment by FizzGamingJR** [comment] 2022-07-16 09:07
> Has there been any updates to fix this? I'd rather not implement a new key system.

I still have this issue on my server, and from my understanding I don't even think it will end up being fixed.
I am on the same level as you, I don't want a new key system, and it's quite annoying when players are getting frustrated at me like it's my fault it's broken...

**Comment by Xodus989** [comment] 2022-07-16 19:13
This issue doesn't fix the bug, but it allows cops to get into the vehicle and at least search it by using a lockpick & bypassing all the animation & searching for keys. I added stuff starting at    local player = QBCore.Functions.GetPlayerData() until the usingAdvanced.

`function LockpickDoor(isAdvanced)
    local ped = PlayerPedId()
    local pos = GetEntityCoords(ped)
    local vehicle = QBCore.Functions.GetClosestVehicle()

    if vehicle == nil or vehicle == 0 then return end
    if HasKeys(QBCore.Functions.GetPlate(vehicle)) then return end
    if #(pos - GetEntityCoords(vehicle)) > 2.5 then return end
    if GetVehicleDoorLockStatus(vehicle) <= 0 then return end

    local player = QBCore.Functions.GetPlayerData()
    PlayerJob = player.job

    if PlayerJob.name == "police" then
        SetVehicleDoorsLocked(vehicle, 1)
        TriggerServerEvent('qb-vehiclekeys:server:AcquireVehicleKeys', QBCore.Functions.GetPlate(vehicle))
        return
    end

    usingAdvanced = isAdvanced
    TriggerEvent('qb-lockpick:client:openLockpick', lockpickFinish)
end`

**Comment by FizzGamingJR** [comment] 2022-07-19 23:59
> This issue doesn't fix the bug, but it allows cops to get into the vehicle and at least search it by using a lockpick & bypassing all the animation & searching for keys. I added stuff starting at    local player = QBCore.Functions.GetPlayerData() until the usingAdvanced.
> 
> 
> 
> `function LockpickDoor(isAdvanced)
> 
>     local ped = PlayerPedId()
> 
>     local pos = GetEntityCoords(ped)
> 
>     local vehicle = QBCore.Functions.GetClosestVehicle()
> 
> 
> 
>     if vehicle == nil or vehicle == 0 then return end
> 
>     if HasKeys(QBCore.Functions.GetPlate(vehicle)) then return end
> 
>     if #(pos - GetEntityCoords(vehicle)) > 2.5 then return end
> 
>     if GetVehicleDoorLockStatus(vehicle) <= 0 then return end
> 
> 
> 
>     local player = QBCore.Functions.GetPlayerData()
> 
>     PlayerJob = player.job
> 
> 
> 
>     if PlayerJob.name == "police" then
> 
>         SetVehicleDoorsLocked(vehicle, 1)
> 
>         TriggerServerEvent('qb-vehiclekeys:server:AcquireVehicleKeys', QBCore.Functions.GetPlate(vehicle))
> 
>         return
> 
>     end
> 
> 
> 
>     usingAdvanced = isAdvanced
> 
>     TriggerEvent('qb-lockpick:client:openLockpick', lockpickFinish)
> 
> end`

I have yet to test this out, but if it works as intended then I appreciate your input.
This bug is ruining my server, and undoubtably others as well, wish there was just a fix or a fork which fixes it.

**Comment by 1david25** [comment] 2022-08-05 04:19
any update to this?

**Comment by FizzGamingJR** [comment] 2022-08-05 08:55
> any update to this?

Not from my knowledge, if it is majorly effecting you try to do the command /givekeys {ID} and it will give the person with that ID keys to your owned vehicle that is out of the garage.
There is also a command to remove the keys which I believe is /takekeys but it may be a bit different.

The chances of this fully being fixed is very slim in my opinion.

**Comment by tom-osborne** [comment] 2022-08-05 13:28
@1david25 @FizzGamingJR  if you want to help out, you can test out my PR, which uses server-sided lock control. It might fix your issues.
https://github.com/qbcore-framework/qb-vehiclekeys/pull/129

**Comment by FizzGamingJR** [comment] 2022-08-05 13:30
> @1david25 @FizzGamingJR  if you want to help out, you can test out my PR, which uses server-sided lock control. It might fix your issues.
> 
> https://github.com/qbcore-framework/qb-vehiclekeys/pull/129
> 
> 

I will certainly check it out, and see if it resolves any of the issues I am currently having. Thank you very much :)

**Closed** 2022-08-14 19:12 UTC
Labels: bug

**Comment by DisguisedOG** [comment] 2022-08-29 12:12
I found a bypass by using B1carremote instead of vehiclekeys
