### ISSUE TITLE
[BUG] Car Jacking is not working Newest qb-core framework install.

### ISSUE THREAD

**Issue by twigmasters** [qbcore-framework/qb-vehiclekeys#194] opened 2023-01-20 09:23 UTC
**Describe the bug**
With a new updated version of qbcore including vehicle keys I was testing the car jacking and when I point a pistol at a NPC in a car nothing happens.  They look at me briefly then drive away. I checked both the server console and client console and no errors. Anyone know how to fix this? 

I already have all the updates because it is a fresh server install.

**Comment by pifaro** [comment] 2023-01-23 16:38
Same issue here. Updated qb-vehicleys and:
Carjacking not working when pointing a gun at driver NPC; NPC driving a car is not locked; Robbing parked cars automatically hotwires it and does not have the option to search for keys

**Comment by pifaro** [comment] 2023-01-25 17:55
Fixed it by updating qb-core

**Comment by twigmasters** [comment] 2023-01-25 19:29
I have the most current version of qb-core and vehicle keys and still same issue i posted above.

**Comment by KamiDaStreet** [comment] 2023-02-11 16:17
I have the same problem

**Comment by Cupidojex** [comment] 2023-05-20 14:03
i have the same!! if this fix,  i need the function  to work!

**Comment by spookstuh** [comment] 2023-05-29 13:07
find fix for this im getting the same problem?

**Comment by KingRyuShin** [comment] 2023-10-06 07:44
Keeping this up, the fix is the put the robloop in a thread and not un a function being called one time

**Comment by L1GHTNINGx** [comment] 2023-11-05 04:56
any fix for this?

**Comment by singh-manavv** [comment] 2023-11-20 20:07
Just tested this , it works perfectly fine. Couldn't reproduce the issue so i will be closing this thread.

**Closed** 2023-11-20 21:25 UTC
Labels: bug
