### ISSUE TITLE
No Keys

### ISSUE THREAD

**Issue by JesseJames804** [qbcore-framework/qb-vehiclekeys#239] opened 2023-10-28 04:04 UTC
Okay so having an issue where if you buy a car you wont get the keys for the vehicle and also the plates are wrong so i have to go into database and change them (heidisql)

**Comment by Swellington-Soares** [comment] 2023-10-31 07:47
I'll investigate, but I don't think so.

**Comment by singh-manavv** [comment] 2023-11-20 18:44
I tested this , couldn't reproduce the issue. So i will be closing this thread.

**Closed** 2023-11-20 21:25 UTC
Labels: bug
