### ISSUE TITLE
[BUG] Not getting keys to vehicles

### ISSUE THREAD

**Issue by Ginjakz** [qbcore-framework/qb-vehiclekeys#197] opened 2023-01-27 13:32 UTC
**Describe the bug**
Random players at random times not getting keys to vehicles they own

**To Reproduce**
It is hard to reproduce as not every user has the issue and it does not happen all the time.  I have seen several users mention this error in previous Bug Reports and in Discord.  There are no Errors in Console, Server or anywhere to try and isolate where it is breaking at.

**Expected behavior**
Get keys to the vehicle

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Fully updated
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] Several
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**

https://user-images.githubusercontent.com/116679253/215099235-a654fb66-91de-478d-9a08-7d4a2e9b5313.mp4

**Comment by thattoxicdorito** [comment] 2023-02-02 20:51
We are also having this problem, on a fresh install. Anyone can buy/spawn their vehicle. But it doesn't actually give you key access. This started as of a week ago from today when we updated.

**Comment by RutsukuFushin** [comment] 2023-02-04 01:41
I may have understood the cause why there is this issue...

The issue is on server side,
 VehicleList is never setted with values at the start. So, each time server restart, each time we must set again VehicleList...

**Comment by sp1d3r1987** [comment] 2023-02-07 10:41
Did you fix this RutsukuFushin?
if so please say how!!
this is driving me insane :@

**Comment by RutsukuFushin** [comment] 2023-02-08 23:23
I didn't really solve it, because I also use okokgarage. But, if I have some time this week-end, I may correct it.

**Comment by Glen92** [comment] 2023-03-09 19:43
i have the same problem anyone has a solution?

**Comment by TinkerGaming87** [comment] 2023-03-16 15:18
has anyone solved this issue

**Comment by Glen92** [comment] 2023-03-19 15:04
still no fix?

**Comment by d-w00d** [comment] 2023-05-21 07:39
No fix, I think it is something to do with the core not the keys or garages, I've used older versions and the issue still persists.

**Comment by GrybasTV** [comment] 2023-06-05 20:58
Is not the keys. Its garage. Giving not your vehicle keys because is not your vehicle

**Comment by KingRyuShin** [comment] 2023-10-06 07:43
commenting to keep this up

**Comment by singh-manavv** [comment] 2023-11-20 20:03
If this was an issue , it has already been fixed in the new patches. So i will be closing this thread

**Closed** 2023-11-20 21:25 UTC
Labels: bug
